apiVersion: batch/v1
kind: Job # Job can use more resources. Pod can only get 2-gpu and 8G memory at most.
metadata:
#   name: qic003-job
#   name: qic003-job-effnetb4-5eps-224
#   name: qic003-job-eval
#   name: qic003-job-resnet101-5eps-168
#   name: qic003-job-resnet50-5eps-168
   name: qic003-job-vgg16-5eps-224
#   name: qic003-job-extract
#   name: effnetb0-5eps-224-s1579
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                 - 1080Ti
#                 - 2080Ti
#                 - V100
#                 - titan-xp
      restartPolicy: Never
      containers:
      - name: gpu-container
        image: liam951120/coralnet:latest
        # https://stackoverflow.com/questions/33887194/how-to-set-multiple-commands-in-one-yaml-file-with-kubernetes
#        args: ["sleep", "infinity"]
        command: ["/bin/bash", "-c"]
        args:
          - source ../miniconda/etc/profile.d/conda.sh;
            conda activate coralnet;
            cd ..;
            cp -r qic003/CoralNet-master ./;
            cd CoralNet-master/;
            chmod +x scripts/train.sh;
            ./scripts/train.sh --net vgg --net_version vgg16 --batch_size 144 --workers 32 --lr 0.0005 --max_lr 0.001 --epoch 5 --suffix "5eps_0001maxlr" --logdir ../qic003/result/224;
#            ./scripts/train.sh --net efficientnet --net_version b0 --dataset coralnet_evaluation_nautilus --source s1579 --batch_size 156 --log_batch 100 --workers 108 --ntclasses 37 --lr 0.005 --max_lr 0.1 --suffix "5eps_01maxlr"  --net_path ../qic003/result/224/efficientnet_b0_coralnet_nautilus_0.05_5eps_01maxlr/0/best.pt --logdir ../qic003/result/evaluation
#            ./scripts/train.sh --net efficientnet --net_version b4 --batch_size 128 --workers 96 --epoch 5 --suffix "5eps_01maxlr" --logdir ../qic003/result/alpha/224;
#            ./scripts/train.sh --net resnet --net_version resnet50 --batch_size 312 --workers 96 --epoch 5 --suffix "5eps_01maxlr" --logdir ../qic003/result/alpha/168;
#            mkdir -p /root/.cache/torch/checkpoints/;
#            cp qic003/pretrained_models/vgg16-397923af.pth /root/.cache/torch/checkpoints/;
#            cp qic003/pretrained_models/efficientnet-b0-355c32eb.pth /root/.cache/torch/checkpoints/;
        volumeMounts:
        - mountPath: /qic003
          name: qic003
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 156Gi
            nvidia.com/gpu: 2
            cpu: "12"
          requests:
            memory: 64Gi
            nvidia.com/gpu: 2
            cpu: "3"
      volumes:
        - name: qic003
          persistentVolumeClaim:
            claimName: qic003
        - name: dshm
          emptyDir:
            medium: Memory
