apiVersion: batch/v1
kind: Job # Job can use more resources. Pod can only get 2-gpu and 8G memory at most.
metadata:
   name: resnet101-100eps-1275-adam
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                 - 1080Ti
#                 - 2080Ti
#                 - V100
#                 - titan-xp
      restartPolicy: Never
      containers:
      - name: gpu-container
        image: liam951120/coralnet:coralnet
        # https://stackoverflow.com/questions/33887194/how-to-set-multiple-commands-in-one-yaml-file-with-kubernetes
        command: ["/bin/bash", "-c"]
        args:
          - source ../miniconda/etc/profile.d/conda.sh;
            conda activate coralnet;
            cp -r qic003/CoralNet-master ./;
            cd CoralNet-master/;
            cp credentials ~/.aws/credentials;
            aws configure set plugins.endpoint awscli_plugin_endpoint;
            aws configure set s3api.endpoint_url https://s3.nautilus.optiputer.net;
            aws configure set s3.endpoint_url https://s3.nautilus.optiputer.net;
            chmod +x scripts/train.sh;
            ./scripts/train.sh --net resnet --net_version resnet101 --batch_size 144 --optim adam --lr 0.001 --lrdecay 0.0001 --workers 36 --epoch 100 --suffix adam --resume -1;
        volumeMounts:
        - mountPath: /qic003
          name: qic003
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 112Gi
            nvidia.com/gpu: 2
            cpu: "6"
          requests:
            memory: 64Gi
            nvidia.com/gpu: 2
            cpu: "4"
      volumes:
        - name: qic003
          persistentVolumeClaim:
            claimName: qic003
        - name: dshm
          emptyDir:
            medium: Memory
