apiVersion: batch/v1
kind: Job # Job can use more resources. Pod can only get 2-gpu and 8G memory at most.
metadata:
  # name: qic003-job-efficientnet
  name: qic003-job-resnet
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                # - 1080Ti
                - 2080Ti
                - V100
                - titan-xp
      restartPolicy: Never
      containers:
      - name: gpu-container
        image: liam951120/coralnet:latest
        # https://stackoverflow.com/questions/33887194/how-to-set-multiple-commands-in-one-yaml-file-with-kubernetes
        # args: ["sleep", "infinity"]
        command: ["/bin/bash", "-c"]
        args:
          - source ../miniconda/etc/profile.d/conda.sh;
            conda activate coralnet;
            cd ..;
            cp -r qic003/CoralNet-master ./;
            cd CoralNet-master/;
            chmod +x scripts/train_resnet.sh;
            ./scripts/train_resnet.sh --batch_size 96 --workers 24 --lr 1.0;
#            chmod +x scripts/train_efficientnet.sh;
#            ./scripts/train_efficientnet.sh --batch_size 156 --workers 48 --resume -1;
        volumeMounts:
        - mountPath: /qic003
          name: qic003
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 56Gi
            nvidia.com/gpu: 1
            cpu: "16"
          requests:
            memory: 56Gi
            nvidia.com/gpu: 1
            cpu: "16"
      volumes:
        - name: qic003
          persistentVolumeClaim:
            claimName: qic003
        - name: dshm
          emptyDir:
            medium: Memory
