apiVersion: v1
kind: Pod # Pod can only get 2-gpu and 8G memory at most.
metadata:
  name: qic003-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu-type
            operator: In
            values:
            - 1080Ti
            - 2080Ti
            - V100
            - titan-xp
  containers:
  - name: gpu-container
    # securityContext:
    #   privileged: true
    #   capabilities:
    #     add:
    #       - SYS_ADMIN
    #image: gitlab-registry.nautilus.optiputer.net/wex041/lab:maskrcnn-benchmark
    # Use image from DockerHub as below since it is more stable.
    image: xwjabc/lab:maskrcnn-benchmark
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /qic003
      name: qic003
    - mountPath: /dev/shm
      name: dshm
    resources:
      limits:
        memory: 8Gi
        nvidia.com/gpu: 1
      requests:
        memory: 8Gi

  restartPolicy: Never
  volumes:
    - name: qic003
      persistentVolumeClaim:
        claimName: qic003
    - name: dshm
      emptyDir:
        medium: Memory
